### ISSUE TITLE
Overlays are in incorrect position

### ISSUE THREAD

**Issue by seitzcasey** [geheur/improvedfragmentui#2]
With the RL update today, the icon overlays are in the incorrect position.
![Untitled](https://user-images.githubusercontent.com/12435220/153217655-cc05d2ac-084a-468f-a9c7-20110650d904.png)

**Comment by geheur** [comment]
based on the update that fragment presets made this should be a very simple fix.

**Comment by geheur** [comment]
This has been fixed in version 1.0.1.
